package com.ew.handscript.network

import com.ew.handscript.model.GlyphModel
import com.ew.handscript.model.LibraryLevel
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ============================================
 * HandCraft Font - 前后端 API 接口契约
 * ============================================
 *
 * 基础URL配置（已在build.gradle中定义）：
 * - 开发环境: https://dev-api.handcraft.font/v1/
 * - 生产环境: https://api.handcraft.font/v1/
 *
 * 认证方式: Bearer Token (JWT)
 * 请求格式: JSON (application/json)
 * 响应格式: JSON (application/json)
 * 编码: UTF-8
 */

// ============================================
// 1. 字形上传相关接口
// ============================================

/**
 * 请求：批量上传字形数据
 * POST /api/v1/glyphs/batch-upload
 */
@Serializable
 data class GlyphBatchUploadRequest(
    @SerialName("batch_id")
    val batchId: String,  // 客户端生成的UUID

    @SerialName("glyphs")
    val glyphs: List<GlyphUploadItem>,

    @SerialName("upload_metadata")
    val uploadMetadata: UploadMetadata
)

@Serializable
 data class GlyphUploadItem(
    @SerialName("unicode")
    val unicode: String,

    @SerialName("character")
    val character: String,

    @SerialName("glyph_version")
    val glyphVersion: Int,

    @SerialName("image_base64")
    val imageBase64: String,  // PNG格式，Base64编码

    @SerialName("width")
    val width: Int,

    @SerialName("height")
    val height: Int,

    @SerialName("baseline")
    val baseline: Int,

    @SerialName("advance_width")
    val advanceWidth: Int,

    @SerialName("tags")
    val tags: List<String> = emptyList(),

    @SerialName("ocr_text")
    val ocrText: String? = null,

    @SerialName("corrected_text")
    val correctedText: String? = null
)

@Serializable
 data class UploadMetadata(
    @SerialName("total_count")
    val totalCount: Int,

    @SerialName("source_type")
    val sourceType: String,  // "scan", "manual_create"

    @SerialName("device_id")
    val deviceId: String,

    @SerialName("client_version")
    val clientVersion: String
)

/**
 * 响应：批量上传结果
 */
@Serializable
 data class GlyphBatchUploadResponse(
    @SerialName("batch_id")
    val batchId: String,

    @SerialName("uploaded_count")
    val uploadedCount: Int,

    @SerialName("failed_items")
    val failedItems: List<FailedUploadItem>,

    @SerialName("storage_urls")
    val storageUrls: Map<String, String>,  // glyphId -> cloud URL

    @SerialName("status")
    val status: String  // "completed", "partial_failed"
)

@Serializable
 data class FailedUploadItem(
    @SerialName("glyph_id")
    val glyphId: String,

    @SerialName("error_code")
    val errorCode: String,

    @SerialName("error_message")
    val errorMessage: String
)

// ============================================
// 2. 字体生成相关接口
// ============================================

/**
 * 请求：提交字体生成任务
 * POST /api/v1/fonts/generate
 */
@Serializable
 data class FontGenerationRequest(
    @SerialName("font_name")
    val fontName: String,  // 用户自定义字体名称

    @SerialName("glyph_set_id")
    val glyphSetId: String,  // 字形集合ID

    @SerialName("font_options")
    val fontOptions: FontGenerationOptions
)

@Serializable
 data class FontGenerationOptions(
    @SerialName("font_family_name")
    val fontFamilyName: String,

    @SerialName("include_fallback_glyphs")
    val includeFallbackGlyphs: Boolean = true,

    @SerialName("hinting_level")
    val hintingLevel: String = "light",  // "none", "light", "full"

    @SerialName("optimize_for_screen")
    val optimizeForScreen: Boolean = true,

    @SerialName("enable_ligatures")
    val enableLigatures: Boolean = false,

    @SerialName("metadata")
    val metadata: FontMetadata = FontMetadata()
)

@Serializable
 data class FontMetadata(
    @SerialName("designer")
    val designer: String = "",

    @SerialName("description")
    val description: String = "Personal handwriting font generated by HandCraft Font",

    @SerialName("copyright")
    val copyright: String = "",

    @SerialName("version")
    val version: String = "1.0"
)

/**
 * 响应：字体生成任务提交结果
 */
@Serializable
 data class FontGenerationResponse(
    @SerialName("task_id")
    val taskId: String,

    @SerialName("status")
    val status: TaskStatus,  // "queued", "processing", "completed", "failed"

    @SerialName("estimated_seconds")
    val estimatedSeconds: Int,  // 预计处理时间

    @SerialName("position_in_queue")
    val positionInQueue: Int
)

@Serializable
 enum class TaskStatus {
    @SerialName("queued") QUEUED,
    @SerialName("processing") PROCESSING,
    @SerialName("completed") COMPLETED,
    @SerialName("failed") FAILED,
    @SerialName("cancelled") CANCELLED
}

/**
 * 请求：查询字体生成任务状态
 * GET /api/v1/fonts/tasks/{task_id}
 */
@Serializable
 data class FontTaskStatusResponse(
    @SerialName("task_id")
    val taskId: String,

    @SerialName("status")
    val status: TaskStatus,

    @SerialName("progress_percent")
    val progressPercent: Int,  // 0-100

    @SerialName("current_stage")
    val currentStage: String,  // "vectorizing", "compiling", "packaging"

    @SerialName("result")
    val result: FontTaskResult? = null,

    @SerialName("error")
    val error: TaskError? = null
)

@Serializable
 data class FontTaskResult(
    @SerialName("download_url")
    val downloadUrl: String,  // .ttf 文件下载链接

    @SerialName("file_size_bytes")
    val fileSizeBytes: Long,

    @SerialName("checksum_sha256")
    val checksumSha256: String,

    @SerialName("font_preview_url")
    val fontPreviewUrl: String,  // 字体预览图

    @SerialName("expiry_time")
    val expiryTime: Long  // 下载链接过期时间（Unix时间戳）
)

@Serializable
 data class TaskError(
    @SerialName("code")
    val code: String,

    @SerialName("message")
    val message: String,

    @SerialName("retryable")
    val retryable: Boolean
)

// ============================================
// 3. OCR纠错相关接口（LLM语义纠错）
// ============================================

/**
 * 请求：提交OCR文本进行语义纠错
 * POST /api/v1/ocr/correct
 */
@Serializable
 data class OcrCorrectionRequest(
    @SerialName("ocr_results")
    val ocrResults: List<OcrResultItem>,

    @SerialName("context_text")
    val contextText: String? = null,  // 前后文文本（可选）

    @SerialName("document_type")
    val documentType: String = "general"  // "general", "formal", "casual"
)

@Serializable
 data class OcrResultItem(
    @SerialName("glyph_id")
    val glyphId: String,

    @SerialName("unicode")
    val unicode: String,

    @SerialName("ocr_text")
    val ocrText: String,

    @SerialName("confidence")
    val confidence: Float,

    @SerialName("bounding_box")
    val boundingBox: BoundingBox? = null
)

@Serializable
 data class BoundingBox(
    @SerialName("x")
    val x: Int,
    @SerialName("y")
    val y: Int,
    @SerialName("width")
    val width: Int,
    @SerialName("height")
    val height: Int
)

/**
 * 响应：OCR纠错结果
 */
@Serializable
 data class OcrCorrectionResponse(
    @SerialName("corrected_results")
    val correctedResults: List<CorrectedResult>,

    @SerialName("model_used")
    val modelUsed: String,  // 使用的LLM模型

    @SerialName("processing_time_ms")
    val processingTimeMs: Int
)

@Serializable
 data class CorrectedResult(
    @SerialName("glyph_id")
    val glyphId: String,

    @SerialName("original_text")
    val originalText: String,

    @SerialName("corrected_text")
    val correctedText: String,

    @SerialName("confidence")
    val confidence: Float,

    @SerialName("is_corrected")
    val isCorrected: Boolean,

    @SerialName("correction_reason")
    val correctionReason: String? = null  // 纠错原因说明
)

// ============================================
// 4. 语音识别相关接口（ASR + LLM）
// ============================================

/**
 * 请求：语音转写
 * POST /api/v1/speech/transcribe
 * Content-Type: multipart/form-data
 *
 * 表单字段：
 * - audio_file: 音频文件（支持 wav, mp3, m4a）
 * - language: "zh-CN"
 * - enable_punctuation: true
 * - remove_filler_words: true  // 去除口语化语气词
 */

/**
 * 响应：语音转写结果
 */
@Serializable
 data class SpeechTranscriptionResponse(
    @SerialName("transcription_id")
    val transcriptionId: String,

    @SerialName("text")
    val text: String,  // 转写后的书面化文本

    @SerialName("original_text")
    val originalText: String,  // 原始ASR结果（含口语化表达）

    @SerialName("segments")
    val segments: List<TranscriptionSegment>,

    @SerialName("duration_seconds")
    val durationSeconds: Float,

    @SerialName("processing_time_ms")
    val processingTimeMs: Int
)

@Serializable
 data class TranscriptionSegment(
    @SerialName("start_time")
    val startTime: Float,

    @SerialName("end_time")
    val endTime: Float,

    @SerialName("text")
    val text: String,

    @SerialName("confidence")
    val confidence: Float
)

// ============================================
// 5. 用户字库管理接口
// ============================================

/**
 * 请求：获取用户字库统计
 * GET /api/v1/library/stats
 */
@Serializable
 data class LibraryStatsResponse(
    @SerialName("total_glyphs")
    val totalGlyphs: Int,

    @SerialName("unique_chars")
    val uniqueChars: Int,  // 不重复汉字数

    @SerialName("library_level")
    val libraryLevel: LibraryLevel,

    @SerialName("progress_percent")
    val progressPercent: Float,  // 向下一等级的进度

    @SerialName("coverage_stats")
    val coverageStats: CoverageStats,

    @SerialName("recent_activity")
    val recentActivity: List<ActivityRecord>
)

@Serializable
 data class CoverageStats(
    @SerialName("common_chars_3500")
    val commonChars3500: Float,  // 常用3500字覆盖率

    @SerialName("general_standard_8105")
    val generalStandard8105: Float,  // 通用规范8105字覆盖率

    @SerialName("total_unicode_cjk")
    val totalUnicodeCjk: Float  // 全部CJK汉字覆盖率
)

@Serializable
 data class ActivityRecord(
    @SerialName("date")
    val date: String,  // ISO 8601

    @SerialName("action")
    val action: String,  // "scan", "verify", "generate_font"

    @SerialName("count")
    val count: Int
)

// ============================================
// 6. 文档解析接口
// ============================================

/**
 * 请求：解析文档（Word/PDF/TXT）
 * POST /api/v1/documents/parse
 * Content-Type: multipart/form-data
 *
 * 表单字段：
 * - document: 文档文件
 * - extract_structure: true  // 是否提取段落层级结构
 */

/**
 * 响应：文档解析结果
 */
@Serializable
 data class DocumentParseResponse(
    @SerialName("document_id")
    val documentId: String,

    @SerialName("file_name")
    val fileName: String,

    @SerialName("text_content")
    val textContent: String,  // 纯文本内容

    @SerialName("paragraphs")
    val paragraphs: List<ParsedParagraph>,

    @SerialName("metadata")
    val metadata: DocumentMetadata
)

@Serializable
 data class ParsedParagraph(
    @SerialName("index")
    val index: Int,

    @SerialName("text")
    val text: String,

    @SerialName("style")
    val style: ParagraphStyle
)

@Serializable
 data class ParagraphStyle(
    @SerialName("is_heading")
    val isHeading: Boolean = false,

    @SerialName("heading_level")
    val headingLevel: Int = 0,

    @SerialName("alignment")
    val alignment: String = "left",  // "left", "center", "right", "justify"

    @SerialName("indent_level")
    val indentLevel: Int = 0
)

@Serializable
 data class DocumentMetadata(
    @SerialName("total_pages")
    val totalPages: Int? = null,

    @SerialName("total_words")
    val totalWords: Int,

    @SerialName("author")
    val author: String? = null,

    @SerialName("title")
    val title: String? = null
)

// ============================================
// 通用响应结构
// ============================================

/**
 * 标准API响应包装
 */
@Serializable
 data class ApiResponse<T>(
    @SerialName("code")
    val code: Int,  // 0 = 成功

    @SerialName("message")
    val message: String,

    @SerialName("data")
    val data: T? = null,

    @SerialName("timestamp")
    val timestamp: Long = System.currentTimeMillis(),

    @SerialName("request_id")
    val requestId: String  // 请求追踪ID
)

/**
 * 分页响应
 */
@Serializable
 data class PaginatedResponse<T>(
    @SerialName("items")
    val items: List<T>,

    @SerialName("total")
    val total: Int,

    @SerialName("page")
    val page: Int,

    @SerialName("page_size")
    val pageSize: Int,

    @SerialName("has_more")
    val hasMore: Boolean
)

/**
 * 错误码定义
 */
object ErrorCodes {
    const val SUCCESS = 0
    const val UNKNOWN_ERROR = 1000
    const val INVALID_PARAMETER = 1001
    const val UNAUTHORIZED = 1002
    const val FORBIDDEN = 1003
    const val NOT_FOUND = 1004
    const val RATE_LIMITED = 1005
    const val FILE_TOO_LARGE = 1006
    const val UNSUPPORTED_FILE_TYPE = 1007
    const val OCR_ENGINE_ERROR = 2001
    const val LLM_SERVICE_ERROR = 2002
    const val FONT_GENERATION_FAILED = 3001
    const val FONT_TASK_TIMEOUT = 3002
    const val STORAGE_FULL = 4001
    const val NETWORK_ERROR = 5001
    const val SERVER_INTERNAL_ERROR = 5002
}
